apiVersion: rbac.authentik.crossplane.io/v1alpha1
kind: UserPermission
metadata:
  annotations:
    meta.upbound.io/example-id: rbac/v1alpha1/userpermission
  labels:
    testing.upbound.io/example-name: global-permission
  name: global-permission
spec:
  forProvider:
    permission: authentik_flows.inspect_flow
    userSelector:
      matchLabels:
        testing.upbound.io/example-name: name

---

apiVersion: authentik.crossplane.io/v1alpha1
kind: Flow
metadata:
  annotations:
    meta.upbound.io/example-id: rbac/v1alpha1/userpermission
  labels:
    testing.upbound.io/example-name: flow
  name: flow
spec:
  forProvider:
    designation: authorization
    name: test-flow
    title: Test flow

---

apiVersion: directory.authentik.crossplane.io/v1alpha1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: rbac/v1alpha1/userpermission
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    name: User
    username: user
