apiVersion: provider.authentik.crossplane.io/v1alpha1
kind: LDAP
metadata:
  annotations:
    meta.upbound.io/example-id: provider/v1alpha1/ldap
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    baseDn: dc=ldap,dc=goauthentik,dc=io
    bindFlowSelector:
      matchLabels:
        testing.upbound.io/example-name: authentik_flow
    name: ldap-app

---

apiVersion: authentik.crossplane.io/v1alpha1
kind: Application
metadata:
  annotations:
    meta.upbound.io/example-id: provider/v1alpha1/ldap
  labels:
    testing.upbound.io/example-name: name
  name: name
spec:
  forProvider:
    name: ldap-app
    protocolProvider: ${authentik_provider_ldap.name.id}
